SistemaInventario/Controllers/ReporteController.cs
using SistemaInventario.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaInventario.Interfaces;
using SistemaInventario.Models;

namespace SistemaInventario.Controllers
{
    [Authorize(Roles = "Empleado")]
    public class ReporteController : Controller
    {
        // Inyencion de dependencias
        private readonly AppDBContext _appDbContext;
        private readonly IExcelReportService _excelService;
        private readonly IPdfReportService _pdfService;

        public ReporteController(AppDBContext appDBContext, IExcelReportService excelService, IPdfReportService pdfService)
        {
            _appDbContext = appDBContext;
            _excelService = excelService;
            _pdfService = pdfService;
        }

        // Lista de los productos en Stock
        public async Task<IActionResult> Stock()
        {
            // Obtener Todo los Productos con su cantidad en Stock
            var productos = await _appDbContext.Productos.ToListAsync();
            return View(productos);
        }

        // Exportar Tabla a Excel
        public async Task<IActionResult> ExportStockExcel()
        {
            var productos = await _appDbContext.Productos.ToListAsync();

            var columns = new Dictionary<string, Func<Producto, object>>
            {
                ["Producto"] = p => p.Nombre,
                ["Codigo"] = p => p.CodigoProducto,
                ["Cantidad en Stock"] = p => p.CantidadStock,
                ["Nivel Mínimo"] = p => 5 // Puedes cambiarlo por p.NivelMinimo si existe
            };

            var stream = await _excelService.GenerateExcelReport(productos, "Stock", columns);

            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "StockReport.xlsx");
        }

        // Exportar Tabla a PDF
        public async Task<IActionResult> ExportStockPDF()
        {
            var productos = await _appDbContext.Productos.ToListAsync();

            var columns = new Dictionary<string, Func<Producto, object>>
            {
                ["Producto"] = p => p.Nombre,
                ["Codigo"] = p => p.CodigoProducto,
                ["Cantidad en Stock"] = p => p.CantidadStock,
                ["Nivel Mínimo"] = p => 5
            };

            var stream = await _pdfService.GeneratePdfReport(productos, "Reporte de Stock", columns);

            return File(stream, "application/pdf", "ReporteStock.pdf");
        }

    }
}

SistemaInventario/Controllers/SearchController.cs
using SistemaInventario.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace SistemaInventario.Controllers
{
    public class SearchController : Controller
    {
        public readonly AppDBContext _appDBContext;

        public SearchController(AppDBContext appDBContext)
        {
            _appDBContext = appDBContext;
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> BuscarUsuario(string? term)
        {
            // Consulta de la BD con Include para evitar N+1
            var query = _appDBContext.Usuarios.Include(p => p.Role).AsQueryable();

            // Aplicar filtro solo si hay término de búsqueda
            if (!string.IsNullOrEmpty(term))
            {
                query = query.Where(u =>
                        u.Nombre.Contains(term) ||
                        u.Correo.Contains(term) ||
                        u.Role.Rol.Contains(term)
                      );
            }

            var usuarios = await query.ToListAsync();

            // Mensaje de feedback
            if (!string.IsNullOrEmpty(term) && !usuarios.Any())
            {
                TempData["Warning"] = $"No se encontraron usuarios para '{term}'.";
            }
            else if (!string.IsNullOrEmpty(term))
            {
                TempData["Success"] = $"Se encontraron {usuarios.Count} usuarios.";
            }

            return View(usuarios);
        }

       
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> BuscarRol(string? term)
        {
            // Consulta de la BD con Include para evitar N+1
            var query = _appDBContext.Roles.AsQueryable();

            // Aplicar filtro solo si hay término de búsqueda
            if (!string.IsNullOrEmpty(term))
            {
                query = query.Where(r =>
                        r.Rol.Contains(term)
                      );
            }

            var roles = await query.ToListAsync();

            // Mensaje de feedback
            if (!string.IsNullOrEmpty(term) && !roles.Any())
            {
                TempData["Warning"] = $"No se encontraron roles para '{term}'.";
            }
            else if (!string.IsNullOrEmpty(term))
            {
                TempData["Success"] = $"Se encontraron {roles.Count} rol.";
            }

            return View(roles);
        }

        
        [Authorize(Roles = "Empleado")]
        [HttpGet]
        public async Task<IActionResult> BuscarProducto(string? term)
        {
            // Consulta de la BD con Include para evitar N+1
            var query = _appDBContext.Productos.Include(p => p.Categoria).AsQueryable();

            // Aplicar filtro solo si hay término de búsqueda
            if (!string.IsNullOrEmpty(term))
            {
                query = query.Where(p =>
                        p.Nombre.Contains(term) ||
                        p.CodigoProducto.Contains(term) ||
                        p.Categoria.Nombre.Contains(term) ||
                        p.PrecioCompra.ToString().Contains(term) ||
                        p.PrecioVenta.ToString().Contains(term) ||
                        p.CantidadStock.ToString().Contains(term));
            }

            var productos = await query.ToListAsync();

            // Mensaje de feedback
            if (!string.IsNullOrEmpty(term) && !productos.Any())
            {
                TempData["Warning"] = $"No se encontraron productos para '{term}'.";
            }
            else if (!string.IsNullOrEmpty(term))
            {
                TempData["Success"] = $"Se encontraron {productos.Count} productos.";
            }

            return View(productos);
        }

        
        [Authorize(Roles = "Empleado")]
        [HttpGet]
        public async Task<IActionResult> BuscarCategoria(string? term)
        {
            var query = _appDBContext.Categorias.AsQueryable();

            if (!string.IsNullOrEmpty(term))
            {
                query = query.Where(c => c.Nombre.Contains(term));
            }

            var categoria = await query.ToListAsync();

            if (!string.IsNullOrEmpty(term) && !categoria.Any())
            {
                TempData["Warning"] = $"No se encontraron categoria para '{term}'.";
            }
            else if (!string.IsNullOrEmpty(term))
            {
                TempData["Success"] = $"Se encontraron {categoria.Count} categoria.";
            }

            return View(categoria);
        }

        
        [Authorize(Roles = "Empleado")]
        [HttpGet]
        public async Task<IActionResult> BuscarMovimiento(string? term)
        {
            // Consulta de la BD con Include para evitar N+1
            var query = _appDBContext.MovimientoInventarios.Include(m => m.Producto).AsQueryable();

            // Aplicar filtro solo si hay término de búsqueda
            if (!string.IsNullOrEmpty(term))
            {
                query = query.Where(m =>
                        m.Movimiento.Contains(term) ||
                        m.Fecha.ToString().Contains(term) ||
                        m.Producto.Nombre.Contains(term) ||
                        m.Cantidad.ToString().Contains(term)
                      );
            }

            var movimientos = await query.ToListAsync();

            // Mensaje de feedback
            if (!string.IsNullOrEmpty(term) && !movimientos.Any())
            {
                TempData["Warning"] = $"No se encontraron Movimientos para '{term}'.";
            }
            else if (!string.IsNullOrEmpty(term))
            {
                TempData["Success"] = $"Se encontraron {movimientos.Count} Movimientos.";
            }

            return View(movimientos);
        }

        
        [Authorize(Roles = "Empleado")]
        [HttpGet]
        public async Task<IActionResult> BuscarReporte(string? term)
        {
            var query = _appDBContext.Productos.AsQueryable();

            if (!string.IsNullOrEmpty(term))
            {
                query = query.Where(p => 
                         p.Nombre.Contains(term) ||
                         p.CantidadStock.ToString().Contains(term) ||
                         p.CodigoProducto.Contains(term)
                    );
            }

            var productos = await query.ToListAsync();

            // Mensaje de feedback
            if (!string.IsNullOrEmpty(term) && !productos.Any())
            {
                TempData["Warning"] = $"No se encontraron productos para '{term}'.";
            }
            else if (!string.IsNullOrEmpty(term))
            {
                TempData["Success"] = $"Se encontraron {productos.Count} productos.";
            }

            return View(productos);
        }

    }
}

SistemaInventario/Views/Reporte/Stock.cshtml
@model List<SistemaInventario.Models.Producto>;

<title>Reporte</title>

<link rel="stylesheet" href="~/css/table.css" />
<link rel="stylesheet" href="~/css/button.css" />
<link rel="stylesheet" href="~/css/alert.css" />

<div class="table-container">

    <h2>Reporte de Productos</h2>

    <div class="header-table">
        <!-- Botones -->
        <div class="btn-container">
            <a asp-controller="Reporte" asp-action="ExportStockExcel" class="btn">
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-file-spreadsheet" width="34" height="34" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M14 3v4a1 1 0 0 0 1 1h4" />
                    <path d="M17 21h-10a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2h7l5 5v11a2 2 0 0 1 -2 2z" />
                    <path d="M8 11h8v7h-8z" />
                    <path d="M8 15h8" />
                    <path d="M11 11v7" />
                </svg>
            </a>

            <a asp-controller="Reporte" asp-action="ExportStockPDF" class="btn">
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-file-type-pdf" width="34" height="34" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M14 3v4a1 1 0 0 0 1 1h4" />
                    <path d="M5 12v-7a2 2 0 0 1 2 -2h7l5 5v4" />
                    <path d="M5 18h1.5a1.5 1.5 0 0 0 0 -3h-1.5v6" />
                    <path d="M17 18h2" />
                    <path d="M20 15h-3v6" />
                    <path d="M11 15v6h1a2 2 0 0 0 2 -2v-2a2 2 0 0 0 -2 -2h-1z" />
                </svg>
            </a>
        </div>

        <!-- Botones de header -->
        <form asp-controller="Search" asp-action="BuscarReporte" method="get">
            <input type="text" name="term" placeholder="Buscar..." class="search-input">
        </form>

    </div>

    <!-- Tablas -->
    <table class="table">
        <thead>
            <tr>
                <th> N° </th>
                <th>Producto</th>
                <th>Código</th>
                <th>Cantidad en Inventario</th>
                <th>Limite Mínimo</th>
            </tr>
        </thead>
        <tbody>
            @{
                int i = 1;
                foreach (var item in Model)
                {
                    <tr>
                        <td>@i</td>
                        <td>@item.Nombre</td>
                        <td>@item.CodigoProducto</td>
                        <td>@item.CantidadStock</td>
                        <td>5</td>
                    </tr>
                    i++;
                }
            }
        </tbody>
    </table>

    <!-- Alertas -->
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success text-center" role="alert">
            @TempData["Success"]
        </div>
    }

    @if (TempData["Warning"] != null)
    {
        <div class="alert alert-warning text-center" role="alert">
            @TempData["Warning"]
        </div>
    }

</div>