SistemaInventario/Controllers/MovimientoController.cs
using SistemaInventario.Data;
using SistemaInventario.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaInventario.ViewModels;

namespace SistemaInventario.Controllers
{
    [Authorize(Roles = "Empleado")]
    public class MovimientoController : Controller
    {

        private readonly AppDBContext _appDbContext;
        public MovimientoController(AppDBContext appDBContext)
        {
            _appDbContext = appDBContext;
        }

        //Vista de tabla de Movimiento del Inventario
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<MovimientoInventario> lista = await _appDbContext.MovimientoInventarios.Include(m => m.Producto).ToListAsync();
            return View(lista);
        }

        // Vista para Crear
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Productos = new SelectList(_appDbContext.Productos, "Id", "Nombre");
            return View();
        }

        // Agregar Movimiento
        [HttpPost]
        public async Task<IActionResult> Create(InventarioVM model)
        {
            if (ModelState.IsValid)
            {
                // Busca el producto seleccionado
                var producto = await _appDbContext.Productos
                    .FirstOrDefaultAsync(p => p.Id == model.ProductoId);

                if (producto == null)
                {
                    ModelState.AddModelError("", "Producto no encontrado.");
                    model.Productos = await _appDbContext.Productos.ToListAsync();
                    return View(model);
                }

                // Actualiza la cantidad en Stock segun el tipo de movimiento
                if (model.Movimiento == "Entrada")
                {
                    producto.CantidadStock += model.Cantidad;

                } else if (model.Movimiento == "Salida") {
                    if (producto.CantidadStock < model.Cantidad)
                    {
                        ModelState.AddModelError("", "La cantidad de salida excede el stock disponible.");
                        model.Productos = await _appDbContext.Productos.ToListAsync();
                        return View(model);
                    }
                    producto.CantidadStock -= model.Cantidad;
                }

                // Crea el movimiento de Inventario
                var movimientoInventario = new MovimientoInventario
                {
                    ProductoId = model.ProductoId,
                    Movimiento = model.Movimiento,
                    Fecha = model.Fecha,
                    Cantidad = model.Cantidad,
                    Descripcion = model.Descripcion,
                };

                // Guardar en la base de datos
                _appDbContext.MovimientoInventarios.Add(movimientoInventario);
                await _appDbContext.SaveChangesAsync();

                TempData["Success"] = "Movimiento Agregado.";
                return RedirectToAction(nameof(Index));
            }

            model.Productos = await _appDbContext.Productos.ToListAsync();
            return View(model);
        }

        // Vista para Editar
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            // Busca el movimiento del producto a editar 
            var movimientoInventario = await _appDbContext.MovimientoInventarios
                .Include(m => m.Producto).FirstOrDefaultAsync(m => m.Id == id);

            if (movimientoInventario == null) { return NotFound(); }

            // Crea los productos
            var productos = await _appDbContext.Productos.ToListAsync();

            var model = new InventarioVM()
            {
                ProductoId = movimientoInventario.ProductoId,
                Movimiento = movimientoInventario.Movimiento,
                Fecha = movimientoInventario.Fecha,
                Cantidad = movimientoInventario.Cantidad,
                Descripcion = movimientoInventario.Descripcion,
                Productos = productos
            };

            return View(model);
        }

        // Editar el movimiento seleccionado por id
        [HttpPost]
        public async Task<IActionResult> Edit(InventarioVM model)
        {
            if (ModelState.IsValid)
            {
                // Busca el Movimiento del Inventario en la BBDD
                var movimientoInventario = await _appDbContext.MovimientoInventarios.FirstOrDefaultAsync(m => m.Id == model.Id);

                // verifica si el mooviento existe
                if (movimientoInventario == null)
                {
                    TempData["Warning"] = "Movimiento no encontrado.";
                    return NotFound();
                }

                // Obtener el producto relacionado con el movimiento
                var producto = await _appDbContext.Productos.FirstOrDefaultAsync(p => p.Id == movimientoInventario.ProductoId);
                if (producto == null)
                {
                    TempData["Warning"] = "Producto no encontrado.";
                    return NotFound();
                }

                // Revertir la cantidad de stock del producto según el movimiento original
                if (movimientoInventario.Movimiento == "Entrada")
                {
                    producto.CantidadStock -= movimientoInventario.Cantidad;
                }
                else if (movimientoInventario.Movimiento == "Salida")
                {
                    producto.CantidadStock += movimientoInventario.Cantidad;
                }

                // Actualiza solo si el valor es no nulo o no vacío
                movimientoInventario.ProductoId = model.ProductoId != 0 ? model.ProductoId : movimientoInventario.ProductoId;
                movimientoInventario.Movimiento = !string.IsNullOrEmpty(model.Movimiento) ? model.Movimiento : movimientoInventario.Movimiento;
                movimientoInventario.Fecha = model.Fecha != DateOnly.MinValue ? model.Fecha : movimientoInventario.Fecha; //Actualiza la fecha si es distindo al anterior
                movimientoInventario.Cantidad = model.Cantidad != 0 ? model.Cantidad : movimientoInventario.Cantidad;
                movimientoInventario.Descripcion = !string.IsNullOrEmpty(model.Descripcion) ? model.Descripcion : movimientoInventario.Descripcion;

                // Volver a obtener el producto en caso de que se haya cambiado el ProductoId
                producto = await _appDbContext.Productos.FirstOrDefaultAsync(p => p.Id == movimientoInventario.ProductoId);
                if (producto == null)
                {
                    TempData["Warning"] = "Producto no encontrado.";
                    return NotFound();
                }

                // Actualizar la cantidad de stock según el nuevo movimiento
                if (movimientoInventario.Movimiento == "Entrada")
                {
                    producto.CantidadStock += movimientoInventario.Cantidad;
                }
                else if (movimientoInventario.Movimiento == "Salida")
                {
                    producto.CantidadStock -= movimientoInventario.Cantidad;
                }

                // Guarda los cambios en la BBDD
                await _appDbContext.SaveChangesAsync();
                // Mensaje de Connfirmación
                TempData["Success"] = "Inventario actualizado correctamente.";
                return RedirectToAction(nameof(Index));
            }

            // Recargal la lista de productos en caso de errores
            model.Productos = await _appDbContext.Productos.ToListAsync();
            return View(model);
        }

        // Eliminar el movimiento seleccionado por id
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            // Busca el movimiento referenciado con producto por su Id
            var movimientoInventario = await _appDbContext.MovimientoInventarios
                .Include(m => m.Producto).FirstAsync(m => m.Id == id);

            // verfica si existe le movimiento del producto
            if (movimientoInventario == null)
            {
                TempData["Warning"] = "Movimiento no encontrado";
                return RedirectToAction(nameof(Index));
            }

            // elimina solo el movimeinto, no el producto
            _appDbContext.MovimientoInventarios.Remove(movimientoInventario);
            await _appDbContext.SaveChangesAsync();

            TempData["Success"] = "Movimiento de Producto eliminado correctamente.";
            return RedirectToAction(nameof(Index));

        }
    }
}

SistemaInventario/Controllers/SearchController.cs
using SistemaInventario.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace SistemaInventario.Controllers
{
    public class SearchController : Controller
    {
        public readonly AppDBContext _appDBContext;

        public SearchController(AppDBContext appDBContext)
        {
            _appDBContext = appDBContext;
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> BuscarUsuario(string? term)
        {
            // Consulta de la BD con Include para evitar N+1
            var query = _appDBContext.Usuarios.Include(p => p.Role).AsQueryable();

            // Aplicar filtro solo si hay término de búsqueda
            if (!string.IsNullOrEmpty(term))
            {
                query = query.Where(u =>
                        u.Nombre.Contains(term) ||
                        u.Correo.Contains(term) ||
                        u.Role.Rol.Contains(term)
                      );
            }

            var usuarios = await query.ToListAsync();

            // Mensaje de feedback
            if (!string.IsNullOrEmpty(term) && !usuarios.Any())
            {
                TempData["Warning"] = $"No se encontraron usuarios para '{term}'.";
            }
            else if (!string.IsNullOrEmpty(term))
            {
                TempData["Success"] = $"Se encontraron {usuarios.Count} usuarios.";
            }

            return View(usuarios);
        }

       
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> BuscarRol(string? term)
        {
            // Consulta de la BD con Include para evitar N+1
            var query = _appDBContext.Roles.AsQueryable();

            // Aplicar filtro solo si hay término de búsqueda
            if (!string.IsNullOrEmpty(term))
            {
                query = query.Where(r =>
                        r.Rol.Contains(term)
                      );
            }

            var roles = await query.ToListAsync();

            // Mensaje de feedback
            if (!string.IsNullOrEmpty(term) && !roles.Any())
            {
                TempData["Warning"] = $"No se encontraron roles para '{term}'.";
            }
            else if (!string.IsNullOrEmpty(term))
            {
                TempData["Success"] = $"Se encontraron {roles.Count} rol.";
            }

            return View(roles);
        }

        
        [Authorize(Roles = "Empleado")]
        [HttpGet]
        public async Task<IActionResult> BuscarProducto(string? term)
        {
            // Consulta de la BD con Include para evitar N+1
            var query = _appDBContext.Productos.Include(p => p.Categoria).AsQueryable();

            // Aplicar filtro solo si hay término de búsqueda
            if (!string.IsNullOrEmpty(term))
            {
                query = query.Where(p =>
                        p.Nombre.Contains(term) ||
                        p.CodigoProducto.Contains(term) ||
                        p.Categoria.Nombre.Contains(term) ||
                        p.PrecioCompra.ToString().Contains(term) ||
                        p.PrecioVenta.ToString().Contains(term) ||
                        p.CantidadStock.ToString().Contains(term));
            }

            var productos = await query.ToListAsync();

            // Mensaje de feedback
            if (!string.IsNullOrEmpty(term) && !productos.Any())
            {
                TempData["Warning"] = $"No se encontraron productos para '{term}'.";
            }
            else if (!string.IsNullOrEmpty(term))
            {
                TempData["Success"] = $"Se encontraron {productos.Count} productos.";
            }

            return View(productos);
        }

        
        [Authorize(Roles = "Empleado")]
        [HttpGet]
        public async Task<IActionResult> BuscarCategoria(string? term)
        {
            var query = _appDBContext.Categorias.AsQueryable();

            if (!string.IsNullOrEmpty(term))
            {
                query = query.Where(c => c.Nombre.Contains(term));
            }

            var categoria = await query.ToListAsync();

            if (!string.IsNullOrEmpty(term) && !categoria.Any())
            {
                TempData["Warning"] = $"No se encontraron categoria para '{term}'.";
            }
            else if (!string.IsNullOrEmpty(term))
            {
                TempData["Success"] = $"Se encontraron {categoria.Count} categoria.";
            }

            return View(categoria);
        }

        
        [Authorize(Roles = "Empleado")]
        [HttpGet]
        public async Task<IActionResult> BuscarMovimiento(string? term)
        {
            // Consulta de la BD con Include para evitar N+1
            var query = _appDBContext.MovimientoInventarios.Include(m => m.Producto).AsQueryable();

            // Aplicar filtro solo si hay término de búsqueda
            if (!string.IsNullOrEmpty(term))
            {
                query = query.Where(m =>
                        m.Movimiento.Contains(term) ||
                        m.Fecha.ToString().Contains(term) ||
                        m.Producto.Nombre.Contains(term) ||
                        m.Cantidad.ToString().Contains(term)
                      );
            }

            var movimientos = await query.ToListAsync();

            // Mensaje de feedback
            if (!string.IsNullOrEmpty(term) && !movimientos.Any())
            {
                TempData["Warning"] = $"No se encontraron Movimientos para '{term}'.";
            }
            else if (!string.IsNullOrEmpty(term))
            {
                TempData["Success"] = $"Se encontraron {movimientos.Count} Movimientos.";
            }

            return View(movimientos);
        }

        
        [Authorize(Roles = "Empleado")]
        [HttpGet]
        public async Task<IActionResult> BuscarReporte(string? term)
        {
            var query = _appDBContext.Productos.AsQueryable();

            if (!string.IsNullOrEmpty(term))
            {
                query = query.Where(p => 
                         p.Nombre.Contains(term) ||
                         p.CantidadStock.ToString().Contains(term) ||
                         p.CodigoProducto.Contains(term)
                    );
            }

            var productos = await query.ToListAsync();

            // Mensaje de feedback
            if (!string.IsNullOrEmpty(term) && !productos.Any())
            {
                TempData["Warning"] = $"No se encontraron productos para '{term}'.";
            }
            else if (!string.IsNullOrEmpty(term))
            {
                TempData["Success"] = $"Se encontraron {productos.Count} productos.";
            }

            return View(productos);
        }

    }
}

SistemaInventario/Views/Movimiento/Create.cshtml
@using SistemaInventario.ViewModels
@model InventarioVM

<title>Registrar Movimiento</title>
<link rel="stylesheet" href="~/css/form.css" />
<link rel="stylesheet" href="~/css/button.css" />
<link rel="stylesheet" href="~/css/alert.css" />

<section class="container">
    <div class="grid-layout">
        <main class="form-container" style="padding: 0px">
            <div class="form-content">
                <h1 class="form-title">Registrar una entrada o salida de Producto</h1>

                <form class="form-grid" asp-controller="Movimiento" asp-action="Create" method="post">

                    <div class="input-group full">
                        <label for="ProductoId" class="label">Producto</label>
                        <select class="input" asp-for="ProductoId" asp-items="ViewBag.Productos">
                            <option value="">Seleccion el Producto</option>
                        </select>
                    </div>

                    <div class="input-group full">
                        <label for="TipoMovimiento" class="label">Tipo de Movimiento</label>
                        <select class="input" asp-for="Movimiento">
                            <option value="Entrada">Entrada</option>
                            <option value="Salida">Salida</option>
                        </select>
                    </div>

                    <div class="input-group">
                        <label for="fecha" class="label">Fecha de Registro</label>
                        <input type="date" id="fecha" class="input" asp-for="Fecha" required />
                    </div>

                    <div class="input-group">
                        <label for="cantidad" class="label">Cantidad</label>
                        <input type="number" id="cantidad" class="input" asp-for="Cantidad" required />
                    </div>

                    <div class="input-group full">
                        <label for="venta" class="label">Descripción</label>
                        <textarea id="venta" class="input" style="height: 50px" asp-for="Descripcion"></textarea>
                    </div>

                    <div class="form-actions">
                        <a class="btn btn-secondary" asp-controller="Movimiento" asp-action="Index">Regresar</a>
                        <button class="btn btn-primary" type="submit">Confirmar</button>
                    </div>

                    @if (TempData["Success"] != null)
                    {
                        <div class="alert alert-success text-center" role="alert">
                            @TempData["Success"]
                        </div>
                    }

                    @if (TempData["Warning"] != null)
                    {
                        <div class="alert alert-warning text-center" role="alert">
                            @TempData["Warning"]
                        </div>
                    }

                    @if (!ViewData.ModelState.IsValid)
                    {
                        <div class="alert input-group full validation-summary-errors">
                            @Html.ValidationSummary()
                        </div>
                    }

                </form>
            </div>
        </main>
    </div>
</section>

SistemaInventario/Views/Movimiento/Edit.cshtml
@using SistemaInventario.ViewModels
@model InventarioVM

<title>Registrar Movimiento</title>
<link rel="stylesheet" href="~/css/form.css" />
<link rel="stylesheet" href="~/css/button.css" />
<link rel="stylesheet" href="~/css/alert.css" />

<section class="container">
    <div class="grid-layout">
        <main class="form-container" style="padding: 0px">
            <div class="form-content">
                <h1 class="form-title">Registrar una entrada o salida de Producto</h1>

                <form class="form-grid" asp-controller="Movimiento" asp-action="Edit" method="post">
                    <input type="hidden" asp-for="Id" />
                    <div class="input-group full">
                        <label for="ProductoId" class="label">Producto</label>
                        <select class="input" asp-for="ProductoId">
                            <option value="">Seleccion el Producto</option>

                            @foreach(var item in Model.Productos)
                            {
                                <option value="@item.Id"> @item.Nombre </option>
                            }

                        </select>
                    </div>

                    <div class="input-group full">
                        <label for="TipoMovimiento" class="label">Tipo de Movimiento</label>
                        <select class="input" asp-for="Movimiento">
                            <option value="Entrada">Entrada</option>
                            <option value="Salida">Salida</option>
                        </select>
                    </div>

                    <div class="input-group">
                        <label for="fecha" class="label">Fecha de Registro</label>
                        <input type="date" id="fecha" class="input" asp-for="Fecha" required />
                    </div>

                    <div class="input-group">
                        <label for="cantidad" class="label">Cantidad</label>
                        <input type="number" id="cantidad" class="input" asp-for="Cantidad" required />
                    </div>

                    <div class="input-group full">
                        <label for="venta" class="label">Descripción</label>
                        <textarea id="venta" class="input" style="height: 50px" asp-for="Descripcion"></textarea>
                    </div>

                    <div class="form-actions">
                        <a class="btn btn-secondary" asp-controller="Producto" asp-action="Index">Regresar</a>
                        <button class="btn btn-primary" type="submit">Confirmar</button>
                    </div>

                    @if (TempData["Success"] != null)
                    {
                        <div class="alert alert-success text-center" role="alert">
                            @TempData["Success"]
                        </div>
                    }

                    @if (TempData["Warning"] != null)
                    {
                        <div class="alert alert-warning text-center" role="alert">
                            @TempData["Warning"]
                        </div>
                    }

                    @if (!ViewData.ModelState.IsValid)
                    {
                        <div class="alert input-group full">
                            @Html.ValidationSummary()
                        </div>
                    }

                </form>
            </div>
        </main>
    </div>
</section>

SistemaInventario/Views/Movimiento/Index.cshtml
@model List<SistemaInventario.Models.MovimientoInventario>;

<title>Movimiento de Inventario</title>

<link rel="stylesheet" href="~/css/table.css" />
<link rel="stylesheet" href="~/css/button.css" />
<link rel="stylesheet" href="~/css/alert.css" />

<div class="table-container">

    <h2>Movimiento de Inventario</h2>

    <div class="header-table">

        <div class="btn-container">
            <a asp-controller="Movimiento" asp-action="Create" class="btn btn-primary">Agregar Movimiento</a>
        </div>

        <!-- Botones de header -->
        <form asp-controller="Search" asp-action="BuscarMovimiento" method="get">
            <input type="text" name="term" placeholder="Buscar..." class="search-input">
        </form>

    </div>

    <table class="table">
        <thead>
            <tr>
                <th>N°</th>
                <th>Tipo de Movimiento</th>
                <th>Fecha</th>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Descripción</th>
            </tr>
        </thead>
        <tbody>
            @{
                int i = 1;
                foreach (var item in Model)
                {
                    <tr>
                        <td>@i</td>
                        <td>@item.Movimiento</td>
                        <td>@item.Fecha.ToString("dd/MM/yyyy")</td>
                        <td>@item.Producto.Nombre</td>
                        <td>@item.Cantidad</td>
                        <td>@item.Descripcion</td>
                        <td>
                            <a class="icon-btn btn-edit" asp-controller="Movimiento" asp-action="Edit" asp-route-id="@item.Id">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
                                </svg>
                            </a>
                            <a class="icon-btn btn-delete" asp-controller="Movimiento" asp-action="Delete" asp-route-id="@item.Id">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                                </svg>
                            </a>
                        </td>
                    </tr>
                    i++;
                }
            }
        </tbody>
    </table>

    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success text-center" role="alert">
            @TempData["Success"]
        </div>
    }
    @if (TempData["Warning"] != null)
    {
        <div class="alert alert-warning text-center" role="alert">
            @TempData["Warning"]
        </div>
    }

    @if (!ViewData.ModelState.IsValid)
    {
        <div class="alert input-group full validation-summary-errors">
            @Html.ValidationSummary()
        </div>
    }

</div>